-- 1. CALLS TABLE (Transaction Data)
create table if not exists calls (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text,
  number text not null,
  status text default 'unread',
  summary text,
  transcript jsonb,
  action_item jsonb,
  audio_url text, 
  duration integer
);

-- 2. SETTINGS TABLE (The Brain's Context)
create table if not exists receptionist_settings (
  id bigint generated by default as identity primary key,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  -- Company Info
  company_name text default 'LCE',
  industry text default 'Technology',
  description text default 'We offer a wide range of tech solutions.',
  
  -- Personality
  greeting_message text default 'Hey, thanks for calling. How can I help?',
  voice_id text default 'alloy',
  
  -- Knowledge
  knowledge_base jsonb default '[]', -- Array of { question, answer }
  custom_vocabulary jsonb default '[]' -- Array of string keywords
);

-- Seed Data (So the app isn't empty)
insert into calls (name, number, status, summary, action_item)
values ('Aayush Sf', '+1 (555) 010-9988', 'unread', 'Customer scheduled a consultation.', '{"type": "calendar", "label": "Appointment Scheduled", "details": "Tomorrow, 2:00 PM"}');

insert into receptionist_settings (company_name, industry, greeting_message, knowledge_base)
values (
  'LCE', 
  'IT Services', 
  'Thanks for calling LCE, how can I help?', 
  '[{"question": "What is the WiFi?", "answer": "Guest123"}]'
);
